stages:
  visualize_data:
    cmd: python src/data_visualization.py
    deps:
      - data/raw/bank-additional-full.csv
    outs:
      - docs/figures/
  data_quality:
    cmd: pytest --html=docs/test_results/reporte_calidad.html --self-contained-html test/test_data_quality.py 
    deps:
      - test/test_data_quality.py
      - data/raw/bank-additional-full.csv
    outs:
    - docs/test_results/reporte_calidad.html

    